---
grails:
  profile: web
  codegen:
    defaultPackage: multikirola
  spring:
    transactionManagement:
      proxies: false
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
endpoints:
  jmx:
    unique-names: true

---
hibernate:
  format_sql: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
---
email:
    testToAddress: "dsantamaria18@gmail.com"
---
environments:
    development:
        uploadFolder: "c:/temp/uploads/multikirolak"
        imgUploadFolder: "c:/temp/uploads/multikirolak/images"
        email:
            from: "appmultikirola@gmail.com"
            userChangeNotificationsTo: "dsantamaria18@gmail.com"
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        uploadFolder: "c:/temp/uploads/multikirolak"
        imgUploadFolder: "c:/temp/uploads/multikirolak/images"
        email:
            from: "appmultikirola@gmail.com"
            userChangeNotificationsTo: "dsantamaria18@gmail.com"
        dataSource:
            pooled: true
            dbCreate: update
            url: jdbc:mysql://vps389236.ovh.net:3306/testdb
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: gobela21
            password: "fadura2017"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 10 * 60000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState;StatementCache(max=200)
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
    production:
        uploadFolder: "/root/ficheros/multikirolak"
        imgUploadFolder: "/root/ficheros/multikirolak/images"
        email:
            from: "appmultikirola@gmail.com"
            userChangeNotificationsTo: "getxomultikirolak@gmail.com"
        dataSource:
            dbCreate: update
#            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#            url: jdbc:mysql://vps389236.ovh.net:3306/gobela21db
            url: jdbc:mysql://localhost:3306/gobela21db
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: root
            password: "*Gobela21$"
#            username: gobela21
#            password: "fadura2017"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
server:
    port: 80
---
grails:
  controllers:
    upload:
      maxFileSize: 5242880
      maxRequestSize: 5242880
---
guide:
  languages:
    - es
    - eu
---
grails:
  mail:
    host: "smtp.gmail.com"
    port: 465
    username: "appmultikirola@gmail.com"
    password: "ivwxffvgjqejwnks"
    #password: "Multikirola_2019"
    props:
      mail.smtp.auth: "true"
      mail.smtp.socketFactory.port: "465"
      mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
      mail.smtp.socketFactory.fallback: "false"
      mail.smtp.starttls.enable: "true"
      mail.smtp.starttls.required: "true"
---
defaultModalidadImg: 'default-modalidad.jpg'
---
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
